### ISSUE TITLE
function to summarise code use from phoebe csv

### ISSUE THREAD

**Issue by nmercadeb** [darwin-eu/CodelistGenerator#146]
This would be useful for phenotypeR, currently it works by getting orphan codes from phoebe, use `summariseAchillesCodeUse`, add relationship to additional columns and change result type to "orphan_codes" so it can use `tableOrphanCodes`

**Comment by edward-burn** [comment]
@nmercadeb @albertpratsu where is this phoebe csv coming from? I'd need to consider if this is something to take a dependency on

**Comment by edward-burn** [comment]
Hmmm it sounds like there is even a new version of phoebe, but I'm not sure @albertpratsu @MaximMoinat what vocabulary verison(s) this is based on or what databases (was it run in any of the darwin data partners)? Is the code used to generate this also open-source (I see csvs floating about, but couldn't find the code behind it - although I only looked very briefly). 

I'm also unclear as to whether pheobe is like achilles results where we assume that data partners have them in the database (in which case like achilles we could incorporate the table in CDMConnector), or if the proposal is that it becomes internal data to this package, or something else?

**Comment by MaximMoinat** [comment]
My understanding is that the concept_recommended table is like study output; it has been once or twice on a set of databases. It is unclear to me on which databases (see also my comment in the OHDSI forum thread Albert refers to). I don't think any of the data partners will have the concept_recommended table loaded.

**Comment by edward-burn** [comment]
Thanks @MaximMoinat I'll leave this issue open in the hope that at some point it becomes clearer how the phoebe output is generated with the potential that it is then run more widely across the network, but until then I don't think CodelistGenerator can build anything on top of it

**Comment by edward-burn** [comment]
I have added support for phoebe results in summariseOrphanCodes https://github.com/darwin-eu/CodelistGenerator/blob/d50d554dc3d5bb642b617758e21f29199d831cca/R/summariseOrphanCodes.R#L65

The way this works is that if phoebe codes exist in the cdm object (in a table called concept_recommended with the format as per the ddl posted on the ohdsi forum), they will be used as additional method for finding orphan codes. In the absence of this table the user will still get results without this additional search (with a message printed that they don't have phoebe in their cdm objects)

Ideally data partners would have this table loaded as part of their ETL, but if they don't the table could be created on a study by study basis (really doesn't seem ideal as it is large and would stay the same until the next release).

@MaximMoinat @albertpratsu @nmercadeb @catalamarti I think this is the most the CodelistGenerator can do. What it then requires is support in omopgenerics https://github.com/darwin-eu-dev/omopgenerics/issues/394 (which I think would then also be automatically supported by CDMConnector) so that if data partners do have the table in their database it will automatically be picked up and included in the cdm reference. And then it would likely need to be checked at onboarding https://github.com/darwin-eu-dev/CdmOnboarding/issues/157
